### ISSUE TITLE
Python Version Check

### ISSUE THREAD

**Issue by androidseb25** [ipv64net/node64_client#89]
Bitte mal ein Check einbauen ob die installierte Python Version kompatible ist mit dem code, 3.7.x ist es nämlich nicht :)

**Comment by androidseb25** [comment]
`Traceback (most recent call last):
  File "node64.py", line 1, in <module>
    from Node64Client import Node64Client
  File "<fstring>", line 1
    (err=)
        ^
SyntaxError: invalid syntax`

**Comment by thethink3r** [comment]
Closes #90
