### ISSUE TITLE
Error when not running as root

### ISSUE THREAD

**Issue by tassilomoedl** [ipv64net/node64_client#9]
Wenn ich das Script als Nicht-Root-User ausführe, bekomme ich(zumindest bei Debian) diesen Fehler: 

IPv64.net - Initialisierung
Wait for next Job.
Wait for next Job.
Wait for next Job.
Start ICMPv4 Task ID: t3AHUznIvaXV
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/icmplib/sockets.py", line 88, in __init__
    self._sock = self._create_socket(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/icmplib/sockets.py", line 486, in _create_socket
    return socket.socket(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/ipv64_client/functions.py", line 33, in icmp
    response_list = ping(icmp_dst, count=icmp_count, interval=icmp_interval, timeout=icmp_timeout, payload_size=icmp_size, family=family)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/icmplib/ping.py", line 141, in ping
    with _Socket(source, privileged) as sock:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/icmplib/sockets.py", line 97, in __init__
    raise SocketPermissionError(privileged)
icmplib.exceptions.SocketPermissionError: Root privileges are required to create the socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/ipv64_client/ipv64_client.py", line 41, in <module>
    task_result = functions.icmp(icmp_dst, icmp_size, icmp_count, icmp_interval, icmp_timeout, 4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ipv64_client/functions.py", line 41, in icmp
    packet_loss = response_list.packet_loss
                  ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'response_list' where it is not associated with a value

**Comment by TwitchCalthaPalustris** [comment]
> icmplib.exceptions.SocketPermissionError: Root privileges are required to create the socket
ICMP verwendet sog. [raw socket](https://en.wikipedia.org/wiki/Berkeley_sockets#Raw_sockets)s, wozu es u.U. entsprechende Berechtigungen braucht.

Mit entsprechenden Berechtigungen funktioniert es natürlich auch ohne root. [Hier](https://stackoverflow.com/questions/37512291/how-is-ping-for-non-root-user-implemented-on-linux-distros) wird das beispielsweise für ping (auf der Konsole) beschrieben.

**Comment by tassilomoedl** [comment]
ok.

**Comment by trevon88** [comment]
Es würde ohne Root laufen wenn man **privileged=False** in der funtions.py setzt.
Wie ich es verstanden habe, übernimmt dann der Host?! Bin bim aber nicht sicher.

Bei dir im Beispiel ist das Line 33
`response_list = ping(icmp_dst, privileged=False, count=icmp_count, interval=icmp_interval, timeout=icmp_timeout, payload_size=icmp_size, family=family)`
